version: '2'

services:
    db:
        image: mysql
        ports:
            - 33060:3306
        volumes:
            - "./var/data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        environment:
            ENV: dev
            DEBUG: 1
    nginx:
        build: nginx
        ports:
            - 8180:80
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 8181:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
