manager:
    resource: "@ManagerBundle/Resources/config/routing.yml"
    prefix:   /manager

app:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    options:
        avanzu_admin_route: welcome
