ManagerBundle\Entity\Broker:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\BrokerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
    oneToOne:
        account:
          targetEntity: ManagerBundle\Entity\Account
          cascade: ["persist", "merge"]
          joinColumn:
            name: account_id
            referencedColumnName: id
    manyToOne:
        type:
            targetEntity: ManagerBundle\Entity\BrokerType
            inversedBy: brokers
            joinColumn:
                name: broker_type_id
                referencedColumnName: id
