ManagerBundle\Entity\BrokerType:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\BrokerTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
    oneToMany:
        brokers:
            targetEntity: ManagerBundle\Entity\Broker
            mappedBy: type
