ManagerBundle\Entity\BrokerMarket:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\BrokerMarketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
    manyToOne:
        broker:
            targetEntity: ManagerBundle\Entity\Broker
            inversedBy: markets
            joinColumn:
                name: broker_id
                referencedColumnName: id
        market:
            targetEntity: ManagerBundle\Entity\Market
            joinColumn:
                name: market_id
                referencedColumnName: id
    manyToMany:
        commissions:
            targetEntity: ManagerBundle\Entity\Commission
            cascade: [ persist, merge, detach, remove ]
            fetch: EXTRA_LAZY
            joinTable:
                name: broker_market_commission
                joinColumns:
                    broker_market_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    commission_id:
                        referencedColumnName: id
                        unique: true
