ManagerBundle\Entity\Broker:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\BrokerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        type:
            type: string
            length: 255
        investment:
            type: float
        capital:
            type: float
    lifecycleCallbacks: {  }
    oneToOne:
        account:
          targetEntity: ManagerBundle\Entity\Account
          cascade: [ persist, merge, detach ]
          joinColumn:
            name: account_id
            referencedColumnName: id
    manyToMany:
        commissions:
            targetEntity: ManagerBundle\Entity\Commission
            cascade: [ persist, merge, detach ]
            fetch: EXTRA_LAZY
            joinTable:
                name: broker_commission
                joinColumns:
                  discr_id: # reference (Broker)
                    referencedColumnName: id
                inverseJoinColumns:
                  commission_id:
                    referencedColumnName: id
                    unique: true
        markets:
            targetEntity: ManagerBundle\Entity\Market
            fetch: EXTRA_LAZY
            joinTable:
                name: broker_market
                joinColumns:
                  broker_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  market_id:
                    referencedColumnName: id
