ManagerBundle\Entity\Broker:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\BrokerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
