ManagerBundle\Entity\Broker:
    type: entity
    repositoryClass: ManagerBundle\Repository\BrokerRepository
    lifecycleCallbacks: {  }
    oneToMany:
        markets:
            targetEntity: ManagerBundle\Entity\BrokerMarket
            cascade: [ persist, merge, detach, remove ]
            mappedBy: broker
            fetch: EXTRA_LAZY
    oneToOne:
        account:
            targetEntity: ManagerBundle\Entity\Account
            cascade: [ persist, merge, detach, remove ]
            joinColumn:
                name: account_id
                referencedColumnName: id
    manyToMany:
        commissions:
            targetEntity: ManagerBundle\Entity\Commission
            cascade: [ persist, merge, detach, remove ]
            fetch: EXTRA_LAZY
            joinTable:
                name: broker_commission
                joinColumns:
                    broker_id: # reference (Broker)
                        referencedColumnName: id
                inverseJoinColumns:
                    commission_id:
                        referencedColumnName: id
                        unique: true
