ManagerBundle\Entity\Commission:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        percentage:
            type: boolean
        value:
            type: float
            nullable: true
        frequency:
            type: string
            length: 255
        applied:
            type: string
            length: 255
    lifecycleCallbacks: {  }
