ManagerBundle\Entity\CommissionType:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\CommissionTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
