ManagerBundle\Entity\Commission:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        commission: ManagerBundle\Entity\Commission
        stock_commission: ManagerBundle\Entity\StockCommission
        market_commission: ManagerBundle\Entity\MarketCommission
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        percentage:
            type: boolean
        value:
            type: float
            nullable: true
        frequency:
            type: string
            length: 255
        applied:
            type: string
            length: 255
    lifecycleCallbacks: {  }
