ManagerBundle\Entity\Country:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\CountryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        iso:
            type: string
            length: 2
            unique: true
        name:
            type: string
            length: 255
            unique: true
        niceName:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        region:
            targetEntity: ManagerBundle\Entity\Region
            inversedBy: countries
            joinColumn:
                name: region_id
                referencedColumnName: id
