ManagerBundle\Entity\Cryptocurrency:
    type: entity
    repositoryClass: ManagerBundle\Repository\CryptocurrencyRepository
    fields:
        name:
            type: string
            length: 255
            unique: true
