ManagerBundle\Entity\Currency:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\CurrencyRepository
    id:
        iso:
            type: string
            length: 3
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
