ManagerBundle\Entity\Currency:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\CurrencyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        iso:
            type: string
            length: 3
            unique: true
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
