ManagerBundle\Entity\Market:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\MarketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        stockIndexes:
            targetEntity: ManagerBundle\Entity\StockIndex
            mappedBy: market
