ManagerBundle\Entity\Market:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        cryptocurrency: ManagerBundle\Entity\CryptoCurrencyMarket
        stock: ManagerBundle\Entity\StockMarket
    fields:
        symbol:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
        alias:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        brokers:
            targetEntity: ManagerBundle\Entity\BrokerMarket
            mappedBy: market
            fetch: EXTRA_LAZY
    manyToOne:
        region:
            targetEntity: ManagerBundle\Entity\Region
            inversedBy: markets
            joinColumn:
                name: region_id
                referencedColumnName: id
        country:
            targetEntity: ManagerBundle\Entity\Country
            inversedBy: markets
            joinColumn:
                name: country_id
                referencedColumnName: id
