ManagerBundle\Entity\Market:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\MarketRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        symbol:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
        alias:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        stocks:
            targetEntity: ManagerBundle\Entity\Stock
            mappedBy: market
    manyToOne:
        region:
            targetEntity: ManagerBundle\Entity\Region
            inversedBy: markets
            joinColumn:
                name: region_id
                referencedColumnName: id
        country:
            targetEntity: ManagerBundle\Entity\Country
            inversedBy: markets
            joinColumn:
                name: country_id
                referencedColumnName: id
