ManagerBundle\Entity\Operation:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\OperationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
        size:
            type: float
        valor:
            type: float
        goal:
            type: float
        stop:
            type: float
        open:
            type: float
        breakeven:
            type: float
            nullable: true
        earnings:
            type: float
            nullable: true
        ratio:
            type: float
        order:
            type: float
            nullable: true
        invested:
            type: float
            nullable: true
        risk:
            type: float
            nullable: true
        commissions:
            type: float
            nullable: true
        benefits:
            type: float
            nullable: true
        taxes:
            type: float
            nullable: true
        benefitsAfterTaxes:
            type: float
            nullable: true
        openedAt:
            type: date
            nullable: true
        closedAt:
            type: date
            nullable: true
        closeReason:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        trades:
            targetEntity: ManagerBundle\Entity\Trade
            mappedBy: operation
            cascade: [ persist, merge, detach, remove ]
            fetch: EXTRA_LAZY
    manyToOne:
        broker:
            targetEntity: ManagerBundle\Entity\Broker
            joinColumn:
                name: broker_id
                referencedColumnName: id
        market:
            targetEntity: ManagerBundle\Entity\BrokerMarket
            joinColumn:
                name: broker_market_id
                referencedColumnName: id
        product:
            targetEntity: ManagerBundle\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
