ManagerBundle\Entity\OperationType:
    type: entity
    table: null
    repositoryClass: ManagerBundle\Repository\OperationTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
