ManagerBundle\Entity\Product:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        cryptocurrency: ManagerBundle\Entity\CryptoCurrency
        stock: ManagerBundle\Entity\Stock
    fields:
        symbol:
            type: string
            length: 255
            unique: true
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
