ManagerBundle\Entity\Product:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        cryptocurrency: ManagerBundle\Entity\CryptoCurrency
        stock: ManagerBundle\Entity\Stock
    fields:
        symbol:
            type: string
            length: 255
            unique: true
        description:
            type: text
            nullable: true
        alias:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        market:
            targetEntity: ManagerBundle\Entity\Market
            joinColumn:
                name: market_id
                referencedColumnName: id
    manyToMany:
        commissions:
            targetEntity: ManagerBundle\Entity\Commission
            cascade: [ persist, merge, detach ]
            fetch: EXTRA_LAZY
            joinTable:
                name: product_commission
                joinColumns:
                  product_id: # reference ()
                    referencedColumnName: id
                inverseJoinColumns:
                  commission_id:
                    referencedColumnName: id
                    unique: true
