ManagerBundle\Entity\StockMarket:
    type: entity
    repositoryClass: ManagerBundle\Repository\StockMarketRepository
    manyToMany:
        stocks:
            targetEntity: ManagerBundle\Entity\Stock
            fetch: EXTRA_LAZY
            joinTable:
                name: broker_market_stock
                joinColumns:
                    broker_market_id: # reference (BrokerMarket)
                        referencedColumnName: id
                inverseJoinColumns:
                    stock_id:
                        referencedColumnName: id
