ManagerBundle\Entity\Stock:
    type: entity
    repositoryClass: ManagerBundle\Repository\StockRepository
    fields:
        company:
            type: string
            length: 255
            unique: true
