ManagerBundle\Entity\StockMarket:
    type: entity
    repositoryClass: ManagerBundle\Repository\StockMarketRepository
    manyToMany:
        stocks:
            targetEntity: ManagerBundle\Entity\Stock
            fetch: EXTRA_LAZY
            joinTable:
                name: market_stock
                joinColumns:
                    market_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    stock_id:
                        referencedColumnName: id
