<?php

namespace ManagerBundle\Repository;

/**
 * BrokerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokerTypeRepository extends CRUDRepository
{
}
