<?php

namespace ManagerBundle\Repository;

use ManagerBundle\Entity\Broker;

/**
 * BrokerMarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokerMarketRepository extends Repository
{
    public function findAllByBroker(Broker $broker)
    {
        return $this->findBy([
            'broker' => $broker
        ]);
    }
}
