<?php

namespace ManagerBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use ManagerBundle\Entity\Account;
use ManagerBundle\Entity\Broker;

/**
 * BrokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokerRepository extends PlatformRepository
{
}
