<?php

namespace ManagerBundle\Repository;

use ManagerBundle\Entity\Account;
use ManagerBundle\Entity\Broker;

/**
 * BrokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokerRepository extends CRUDRepository
{
    /**
     * @param Account $account
     *
     * @return Broker
     */
    public function findByAccount(Account $account)
    {
        return $this->findOneBy([
            'account' => $account
        ]);
    }
}
