<?php

namespace ManagerBundle\Repository;

/**
 * CommissionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionTypeRepository extends CRUDRepository
{
}
