<?php

namespace ManagerBundle\Repository;

use Doctrine\Common\Collections\Collection;

/**
 * CommissionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionTypeRepository extends CRUDRepository
{
    /**
     * @param Collection $commissionTypes
     */
    public function saveBatch(Collection $commissionTypes): void
    {
        $em = $this->getEntityManager();

        foreach ($commissionTypes as $commissionType) {
            $em->persist($commissionType);
        }

        $em->flush();
    }
}
