<?php

namespace ManagerBundle\Repository;

/**
 * CryptocurrencyMarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CryptocurrencyMarketRepository extends MarketRepository
{
}
