<?php

namespace ManagerBundle\Repository;

/**
 * CryptocurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CryptocurrencyRepository extends CRUDRepository
{
}
