<?php

namespace ManagerBundle\Repository;

/**
 * MarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketRepository extends CRUDRepository
{
}
