<?php

namespace ManagerBundle\Repository;

use ManagerBundle\Entity\OperationType;

/**
 * OperationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(OperationType $operationType): void
    {
        $em = $this->getEntityManager();
        $em->persist($operationType);
        $em->flush();
    }
}
