<?php

namespace ManagerBundle\Repository;


/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends CRUDRepository
{
}
