<?php

namespace ManagerBundle\Repository;

/**
 * StockMarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockMarketRepository extends MarketRepository
{
}
