<?php

namespace ManagerBundle\Repository;

/**
 * TransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferRepository extends CRUDRepository
{
}
