markets_stock_market:
    resource: "@ManagerBundle/Resources/config/routing/stock_market.yml"
    prefix:   /stock_market

markets_cryptocurrency_market:
    resource: "@ManagerBundle/Resources/config/routing/cryptocurrency_market.yml"
    prefix:   /cryptocurrency_market