parameters:
    broker_type:
      - stocks
      - cryptocurrencies
    commission_type:
      - buy
      - sell
      - custody
      - initial_margin
      - maintenance_margin
    commission_period:
      - only_one
      - daily
      - monthy
      - yearly
    commission_applied:
      - per_stock
      - per_currency
      - per_amount
      - fixed
    operation_type:
      - short
      - long
    operation_close_reason:
      - goal_reached
      - stop_loss
      - caution_stop_loss
      - trend_deterioration

services:
    manager.broker.markers.transformer:
        class: ManagerBundle\Form\DataTransformer\BrokerMarketToMarketTransformer
        arguments: ["@=container.get('doctrine').getManager().getRepository('ManagerBundle:BrokerMarket')"]
        tags: [form.type]

    ManagerBundle\Form\BrokerType:
        arguments: ["%broker_type%", "@manager.broker.markers.transformer"]
        tags: [form.type]

    ManagerBundle\Form\BrokerMarketEntityType:
        arguments: ["@manager.broker.markers.transformer"]
        tags: [form.type]

    ManagerBundle\Form\CommissionType:
        arguments: ["%commission_type%", "%commission_period%", "%commission_applied%"]
        tags: [form.type]

    ManagerBundle\Form\MarketCommissionType:
        arguments: ["%commission_type%", "%commission_period%", "%commission_applied%"]
        tags: [form.type]

    ManagerBundle\Form\NewOperationType:
        arguments:
          - "%operation_type%"
          - "@=container.get('doctrine').getManager().getRepository('ManagerBundle:Broker')"
          - "@=container.get('doctrine').getManager().getRepository('ManagerBundle:BrokerMarket')"
        tags: [form.type]