manager_index:
    path:     /
    defaults: { _controller: ManagerBundle:Default:index }
    methods:  GET
    options:
        avanzu_admin_route: manager

manager_markets:
    resource: "@ManagerBundle/Resources/config/routing/market.yml"
    prefix:   /markets

manager_stocks:
    resource: "@ManagerBundle/Resources/config/routing/stock.yml"
    prefix:   /stocks