services:
#    manager.example:
#        class: ManagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    manager.broker.saved.transfer:
        class: ManagerBundle\EventListener\SavedTransfer\BrokerListener
        arguments: ["@=container.get('doctrine').getManager().getRepository('ManagerBundle:Broker')"]
        tags:
            - { name: kernel.event_listener, event: crud.post_saved.Transfer, method: onSavedTransfer }

    manager.commissiontype.saved.broker:
        class: ManagerBundle\EventListener\SavedBroker\CommissionTypeListener
        arguments: ["@=container.get('doctrine').getManager().getRepository('ManagerBundle:CommissionType')"]
        tags:
            - { name: kernel.event_listener, event: crud.post_saved.Broker, method: onSavedBroker }
