imports:
    - { resource: "forms.yml" }

services:
#    manager.example:
#        class: ManagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ManagerBundle\Twig\ManagerExtension:
        tags: [twig.extension]

    manager.broker.saved.transfer:
        class: ManagerBundle\EventListener\SavedTransfer\BrokerListener
        arguments: ["@=container.get('doctrine').getManager().getRepository('ManagerBundle:Broker')"]
        tags:
            - { name: kernel.event_listener, event: crud.post_saved.Transfer, method: onSavedTransfer }
