parameters:
    commission_period:
      - only_one
      - daily
      - monthy
      - yearly
    commission_type:
      - buy
      - sell
      - custody
      - initial_margin
      - maintenance_margin

services:
#    manager.example:
#        class: ManagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ManagerBundle\Form\BrokerCommissionType:
            arguments: ["%commission_type%", "%commission_period%"]
            tags: [form.type]

    manager.broker.saved.transfer:
        class: ManagerBundle\EventListener\SavedTransfer\BrokerListener
        arguments: ["@=container.get('doctrine').getManager().getRepository('ManagerBundle:Broker')"]
        tags:
            - { name: kernel.event_listener, event: crud.post_saved.Transfer, method: onSavedTransfer }
