parameters:
    broker_type:
      - stocks
      - cryptocurrencies
    commission_type:
      - buy
      - sell
      - custody
      - initial_margin
      - maintenance_margin
    commission_period:
      - only_one
      - daily
      - monthy
      - yearly
    commission_applied:
      - per_stock
      - per_amount

services:
#    manager.example:
#        class: ManagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ManagerBundle\Twig\ManagerExtension:
            tags: [twig.extension]

    ManagerBundle\Form\BrokerType:
            arguments: ["%broker_type%"]
            tags: [form.type]

    ManagerBundle\Form\CommissionType:
            arguments: ["%commission_type%", "%commission_period%", "%commission_applied%"]
            tags: [form.type]

    manager.broker.saved.transfer:
        class: ManagerBundle\EventListener\SavedTransfer\BrokerListener
        arguments: ["@=container.get('doctrine').getManager().getRepository('ManagerBundle:Broker')"]
        tags:
            - { name: kernel.event_listener, event: crud.post_saved.Transfer, method: onSavedTransfer }
